**Import basics for the file to read csv and concat it as one file and save it.**

In [9]:
import numpy as np 
import pandas as pd

In [11]:
concat_df = pd.concat(map(pd.read_csv, ['/content/dataset_attack.csv',
                                       '/content/dataset_normal.csv']))

In [13]:
nRow, nCol = concat_df.shape
print(f' There are {nRow} rows and {nCol} columns')

 There are 5658998 rows and 29 columns

In [12]:
concat_df.to_csv("normalattack.csv")
!cp normalattack.csv "/content/"

cp: 'normalattack.csv' and '/content/normalattack.csv' are the same file

In [14]:
concat_df

,frame.encap_type,frame.len,frame.protocols,ip.hdr_len,ip.len,ip.flags.rb,ip.flags.df,p.flags.mf,ip.frag_offset,ip.ttl,...,tcp.flags.cwr,tcp.flags.ecn,tcp.flags.urg,tcp.flags.ack,tcp.flags.push,tcp.flags.reset,tcp.flags.syn,tcp.flags.fin,tcp.window_size,tcp.time_delta
1,212,eth:ethertype:ip:udp:data,20,198,0,0,0,0,112,17,...,0,0,0,0,0,0,0,0,0.000000,attack
1,212,eth:ethertype:ip:udp:data,20,198,0,0,0,0,112,17,...,0,0,0,0,0,0,0,0,0.000000,attack
1,212,eth:ethertype:ip:udp:data,20,198,0,0,0,0,112,17,...,0,0,0,0,0,0,0,0,0.000000,attack
1,212,eth:ethertype:ip:udp:data,20,198,0,0,0,0,112,17,...,0,0,0,0,0,0,0,0,0.000000,attack
1,62,eth:ethertype:ip:udp:data,20,48,0,0,0,0,128,17,...,0,0,0,0,0,0,0,0,0.000000,attack
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,60,eth:ethertype:ip:tcp,20,40,0,1,0,0,128,6,...,0,0,1,0,0,0,0,16560,0.001240,normal
1,1434,eth:ethertype:ip:tcp,20,1420,0,1,0,0,113,6,...,0,0,1,0,0,0,0,65019,0.002506,normal
1,60,eth:ethertype:ip:tcp,20,40,0,1,0,0,128,6,...,0,0,1,0,0,0,0,16560,0.001244,normal
1,1434,eth:ethertype:ip:tcp,20,1420,0,1,0,0,113,6,...,0,0,1,0,0,0,0,65019,0.002505,normal
1,1434,eth:ethertype:ip:tcp,20,1420,0,1,0,0,113,6,...,0,0,1,0,0,0,0,65019,0.003997,normal